#!/bin/bash
#find -type f -iname '*.gif' | rev | cut -d '/' -f 1 | cut -d '.' 2- | rev | LC_ALL=C sort -f
find . -type f -iname "*.gif" -exec bash -c 'echo "${0##*/}" | rev | cut -c 5- | rev' {} \; | LC_ALL=C sort -f
